### ISSUE TITLE
怎么获得TKK

### ISSUE THREAD

**Issue by ChaoCaiGuo** [VictorZhang2014/free-google-translate#3]
您好  请问一下TKK是怎么获得的？
我尝试了无论是在java的代码还是python的代码，调用update_TKK()都会出现问题
在网上找了找，说TKK是在 translate.google.cn 这个网页源代码中有，但我在网页源代码并没有找到

以及Android可以webView控件调用本地html文件，在html内嵌js来调用wo()来获取tk（算是种笨方法）。
以及Android的sendGet()方法似乎有错误，会报错no protocol。我直接改用okhttp来获取到数据

**Comment by VictorZhang2014** [comment]
你好，我这个代码内置了tkk获取方法，主要处理tkk的是Python目录下的token.js文件，而在Python端调用是
![image](https://user-images.githubusercontent.com/6853884/107637039-82d16a80-6ca8-11eb-9cce-09404b432043.png)

有任何问题，可以继续追问，

新年快乐~

**Comment by ChaoCaiGuo** [comment]
你好，新年快乐
我尝试调用了update_TKK()，结果控制台并没有输出TKK。我对python不太熟悉，不清楚是什么问题。我根据java的代码推测，update_TKK()方法是获取网页的源代码再匹配tkk，但现在我直接通过网页的源代码也并没有找到tkk
![捕获](https://user-images.githubusercontent.com/27630085/107664554-720efd80-6c84-11eb-8ebd-30d942c34d43.PNG)

**Comment by 969335755** [comment]
![a](https://user-images.githubusercontent.com/27630085/107664906-cade9600-6c84-11eb-8bcc-ee55f9a4228b.PNG)

**Comment by ChaoCaiGuo** [comment]
通过浏览器自带开发者工具测试
谷歌翻译已经更改了新的翻译请求方式，但旧方式尚未失效
![捕获2](https://user-images.githubusercontent.com/27630085/107977732-810eec00-6fb3-11eb-9038-ebfcba2bd053.PNG)
![捕获1](https://user-images.githubusercontent.com/27630085/107977739-82d8af80-6fb3-11eb-884f-eefc3b02b85d.PNG)
请求正文UrlEncode解码后的是[[["MkEWBc","[[\"tange\",\"auto\",\"zh-CN\",true],[null]]",null,"generic"]]]
现在就怕旧方式失效

**Comment by GuoFangPeng** [comment]
谷歌翻译已经更改了新的翻译请求方式post，但旧方式get尚未失效。
等大神抓包解析出新的post参数再说. _(:з)∠)_

**Comment by VictorZhang2014** [comment]
<img width="954" alt="WX20210220-150916@2x" src="https://user-images.githubusercontent.com/6853884/108587253-a2921e00-738d-11eb-9b25-7ad44d3bd4e2.png">
我刚才又运行了一下，这个文件配置良好，没有任何错误，你看截图，翻译代码都是正常运行的，具体逻辑你可以看下GoogleTrans.py文件


另外，回答一下update_TKK()的问题，tkk是一个google的web端翻译的验证机制，也就是说，每次调用改接口，都需要update一下tkk

关于google是否更新了他们翻译接口验证方式，我之前的调研时，google经常改，但是旧的调用方式不会立刻失效，一般可以用1-2年

如果你对Python不熟悉，用java也一样，你可以参考我的Python代码的`self.construct_url()`函数，这个是组装请求的URL的，如果你用`GoogleTrans.py`输出url，等于以下
`https://translate.google.cn/translate_a/single?client=webapp&sl=auto&tl=zh-CN&hl=zh-CN&dt=at&dt=bd&dt=ex&dt=ld&dt=md&dt=qca&dt=rw&dt=rm&dt=ss&dt=t&otf=2&ssel=0&tsel=0&kc=1&tk=771228.877934&q=Hello%20world`

这个URL的翻译结果如截图所示，这个URL是get请求，可以在浏览器上直接运行

不好意思，过年这几天，没用电脑，这不刚回来

**Comment by ChaoCaiGuo** [comment]
感谢解答，我之前出现的问题都在tkk上。
翻译部分到是没有什么大问题。
在更新tkk出现问题后，我尝试按照网上的步骤，去获取tkk。但都获取失败，后面自己尝试通过浏览器自带开发者工具抓包，发现谷歌在现在的网页端已经改用post方法，所以才有疑问
